name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Xcodebuild Action
      uses: sersoft-gmbh/xcodebuild-action@v1.8.0
      with:
        workspace: SwiftyUpdateKit.xcworkspace
        scheme: SwiftyUpdateKit
        destination: 'platform=iOS Simulator, name:iPhone 12 Pro Max'
        action: test
